import streamlit as st

st.title('Swale')

st.header('Design and Maintenance Options')
st.subheader('Watershed Characteristics')
drainage_area = st.number_input('Drainage Area (ac)', value=2, step=1)
impervious_cover = st.number_input('Drainage Area Impervious Cover (pct)', value=40)
land_use_type = st.selectbox('R: Residential, C: Commercial, Ro: Roads, I: Industrial')

st.subheader('Design & Maintenance Options')
level_of_maintenance = st.selectbox('H: High, M: Medium, L: Low')

st.subheader('Whole Life Cost Options')
discount_rate = st.number_input('Discount Rate (%)', value=5.5)

st.header('Method A: Simple Cost based on Drainage Area')
st.subheader('Cost based on Drainage Area')
drainage_area = st.number_input('Drainage Area (DA) (acres)', value=2)
base_facility_cost = st.number_input('Base Facility Cost per acre DA ($)', value=3000)
default_cost_adjustment = st.number_input('Default Cost Adjustment fro Smaller Projects', value=2.2)
resulting_base_cost = st.number_input('Resulting Base Cost per acre DA ($)', value=6600)
base_facility_cost = st.number_input('Base Facility Cost (rounded p to nearest $100) ($)', value=13200)
engineering_and_planning = st.number_input('Engineering & Planning (default = 25% of Base Cost) ($)', value=3300)
land_cost = st.number_input('Land Cost ($)', value=0)
other_cost = st.number_input('Other Costs ($)', value=0)

st.header('Method B: User-Entered Engineers Estimate')
st.subheader('Total Facility Base Costs')
mobilization = st.number_input('Mobilization (LS)')
clearing_and_grubbing = st.number_input('Clearing & Grubbing (AC)')
excavation = st.number_input('Excavation/Grading (CY)')
dewatering = st.number_input('Dewatering (LS)')
haul_of_excavated_material = ('Haul/Dispose of Excavated Material (CY)')
sediment_pretreatment_struct = st.number_input('Sediment Pretreatment Struct (e.g.,inlet sump) (LF)')
inflow_structure = st.number_input('Inflow Structure(s) (LS)')
energy_dissipation_apron = st.number_input('Energy Dissipation Apron (LS)')
overflow_structure = st.number_input('Overflow Structure (concrete or rock riprap) (CY)')
revegetation_controls = st.number_input('Revegetation/Erosion Controls (SY)')
traffic_control = st.number_input('Traffic Control')
signage_public_education_materials = st.number_input('Signage, Public Education Materials,etc (LS)')

st.subheader('Associated Capital Cots')
project_management = ('Project Management')
engineering_preliminary = st.number_input('Engineering: Preliminary')
engineering_final_design = st.number_input('Engineering; Final Design')
topographic_survey = st.number_input('Topographic Survey')
geotechnical = st.number_input('Geotechnical')
landscape_design = st.number_input('Landscape Design')
land_acquisition = st.number_input('Land Acquisition (site, easements, etc)')
utility_relocation = st.number_input('Utility Relocation')
legal_services = st.number_input('Legal Services')
permitting_and_construction_inspection = st.number_input('Permitting & Construction Inspection')
sales_tax = st.number_input('Sales Tax')
contingency = st.number_input('Contingency (e.g. 30%)')

st.header('Maintenance Costs')
st.subheader('Routine Maintenance Activities( Frequent, scheduled events')

st.header('Cost Summary')
st.subheader('Capital Costs')
total_base_facility_cost = st.number_input('Total Base Facility Cost')
total_associated_capital_cost = st.number_input('Total Associated Capital Cost')
